GET http://localhost:3000/api/questions/

###

POST http://localhost:3000/api/questions/
content-type: application/json

{
    "title" : "Chart and Stuff",
    "rating" : "Medium",
    "description" : "Build a histogram chart from a list of randomly-generated numbers",
    "details":
        {
            "prompt" : "Something Something",
            "example" : "blah blah blah example",
            "code" : "console.log()"
        }
                                                                                             
    
}