GET http://localhost:4000/questions

###

GET http://localhost:4000/questions/623c190122bb073f3b6e1529

###

POST  http://localhost:4000/
Content-Type: application/json

{
    "questionTitle" : "What your planet ?",
    "answer" : "Mars"
}
###

PATCH  http://localhost:4000/questions/623c190122bb073f3b6e1529
Content-Type: application/json

{
    "questionTitle" : "What is your last name ?",
    "answer" : "My name is Son"
}
###


DELETE http://localhost:4000/questions/623c190122bb073f3b6e1529